### PR TITLE
Add :Gx, :Gwa, :Gwqa and :Gxa commands

### PR DESCRIPTION
**Pull request by Felixoid**
Hey dear Tim,
I'd like to improve UX a little bit.

In the patch, I've added `:Gwa` command that I miss so much in the daily work. At the same time, to save some keystrokes and provide the same behavior as vim, I've added `:Gx[a]` commands.

Hopefully, you find it useful!

### CODE REVIEW

**Comment by tpope** [comment]
What happens when you call these while some non-Fugitive buffers are open?

**Comment by Felixoid** [comment]
Thank you for asking. I've checked and it doesn't look to work as expected. Looks like the first `exe "wa"` is ignored. Let me work it around a little bit.

**Comment by Felixoid** [comment]
So, here's a terminal record for the testing session, it can be replayed with `asciinema play gwa.txt` 
[gwa.txt](https://github.com/tpope/vim-fugitive/files/6911886/gwa.txt)

The only one side effect I could find is replacing some spaces in the help page buffer with tabs.

**Comment by tpope** [comment]
Your asciinema also shows several `fugitive: file does not belong to a Git repository` errors too, presumably due to the help buffer. And help buffers are just one of numerous possible problematic buffers. The quickfix list, terminal buffers, readonly files, directory buffers (netrw), `http://` buffers, and files in `.gitignore` are the first handful that come to mind. I would expect a robust implementation to be significantly larger than a one liner.

But even with a robust implementation, I'm not sure this is a good idea. If I have files open from multiple repositories, should `:Gwa` stage all of them? Staging files across a bunch of unrelated repositories strikes me as more dangerous than helpful. Should we stage untracked files? If so, there's `:Git add -A`, and if not, there's `:Git add -u`. I don't think `:Gwa` adds much here.

**Comment by Felixoid** [comment]
Thank you for feedback. It makes sense, especially with `:G add -u`

Would you consider meeting only first commit, maybe?

**Comment by tpope** [comment]
From the help:

```
:[range]x[it][!] [++opt] [file]
			Like ":wq", but write only when changes have been
			made.
```

If no changes have been made, should we still stage the file? The fact there is no obvious answer to this question inclines me not to add the command.

**Comment by tpope** [comment]
Now that I think about it, your patch doesn't even implement the normal distinction between `:wq` and `:x`. I don't think Fugitive should provide a `:Gx` that is unrelated to `:x`, especially since the only benefit seems to be one less character to type.

**Comment by Felixoid** [comment]
> Now that I think about it, your patch doesn't even implement the normal distinction between `:wq` and `:x`. I don't think Fugitive should provide a `:Gx` that is unrelated to `:x`, especially since the only benefit seems to be one less character to type.

Quite honest. Thank you for your feedback!

**Pull request closed without merging**
