### PR TITLE
Vim8 terminal support

### PR DESCRIPTION
**Pull request by tracyone**
see following video:

https://asciinema.org/a/IRbMiGITFNl3I5SMoo06DxQOI

update video

### CODE REVIEW

**Comment by coot** [comment]
This indeed fixes the fugitive in vim with `+terminal` feature. @tracyone could you remove the dot to fix the commit message.

@tpope sooner or later any fugitive user will be hit by this.  vim devs are working hard on the `+terminal` feature. Not everything works yet (from the more important things scrolling is not working, but beside that the vim terminal works pretty well), and there is steady progress on it.

**Comment by tracyone** [comment]
@coot In this patch, I split window instead of a new tab.Now I think maybe a new tab is a better choice. What do you think?

**Comment by tracyone** [comment]
Done. Same action with neovim.

**Comment by coot** [comment]
@tracyone why did you closed this? Was it fixed in fugitive?

**Pull request closed without merging**
