### PR TITLE
Use the neovim terminal emulator for StagePatch()

### LINKED ISSUE #618: Gstatus "p" shortcut endless loop
This issue happens in neovim only.

When press "p" in Gstatus window, vim keeps asking for decision but  never responses to any keys. it caused vim to become unresponsive.

### PR DESCRIPTION
**Pull request by Tranquility**
This fixes #618

### CODE REVIEW

**Comment by Tranquility** [comment]
I just realized that TabClosed was added only to neovim so another `if has('nvim')` is needed but please tell me if merging neovim specific stuff is even an option for you.

**Comment by tpope** [comment]
Yeah definitely leave that out of this commit.

Is there a feature (e.g. `has('term')`) we can use instead of checking for nvim in particular?

**Comment by Tranquility** [comment]
> Yeah definitely leave that out of this commit.

Do you mean I should just remove it instead of wrapping it into another if statement? This would mean the status is not updated.

> Is there a feature (e.g. has('term')) we can use instead of checking for nvim in particular?

No, because neovim is always built with all features. We might have a problem with older versions but since it's alpha state we can expect everyone to update regularly.

**Comment by tpope** [comment]
Oh, I see. Can you get a buffer id back from `:term`? The closing of that buffer seems like the relevant event to target.

**Comment by noahfrederick** [comment]
>> Is there a feature (e.g. has('term')) we can use instead of checking for nvim in particular?
>
> No, because neovim is always built with all features. We might have a problem with older versions but since it's alpha state we can expect everyone to update regularly.

You can check `exists(":terminal")`.

**Comment by Tranquility** [comment]
I now use a BufDelete and the terminal buffer naming convention to update whenever a git command was executed in a terminal buffer.

I also added `call s:ExecuteInTree(..)` to make it work in subdirectories. It looks however like there is a race condition, when doing the `git add` the cwd gets reset to early. The `git reset` case works fine.
Do you have any idea how we can solve this?

**Comment by tpope** [comment]
For starters I think you should be fixing the `:Git` command rather than this one particular special case.

**Comment by Tranquility** [comment]
I decided to fix this special case because it is the only one (that I know of) that needs a tty. But I can move the fix into into the `Git` function if you prefer that.

Do you know how `git add --patch` differs from `git reset --patch` that one works while the other doesn't?

**Comment by tpope** [comment]
Oh, that's really bizarre that those two commands differ. But I don't see a harm in routing all commands through `:terminal`. There are definitely other commands (such as `git rebase -i`) for which I would expect it to be necessary.

**Comment by Tranquility** [comment]
I found out why they differ. Pressing <kbd>p</kbd> on a staged file executes `git reset --patch --` instead of `git reset --patch -- /path/to/file`

**Comment by tpope** [comment]
Good catch. I'll definitely fix that.

**Comment by Tranquility** [comment]
> I can see that this mimics Vim's behavior, which uses the whole terminal window though - so maybe there should be an option?

That's why I decided to use a tab and I felt that most hunks do not fit into a split buffer.

**Comment by tpope** [comment]
Okay I've merged after the following fixes:

* Ensuring the chdir to the repo's tree root does not affect the existing buffer.
* Checking for `exists(':terminal')` rather than `has('nvim')`.
* Reloading the status after all terminal buffer deletions, because the git executable might not start with `git` (could be an absolute path, or a wrapper like hub).
* Disabling the explicit status reload except on Windows, where the autocommand is disabled.

The new tab indeed feel odd, but I'm really struggling to see a split as an improvement.

**Comment by blueyed** [comment]
Just for reference, it has been merged in 4cc201cbe3a0c3faa4cde1b82ba941d410e5e81c.

**Comment by sirex** [comment]
Just upgraded fugitive and was surprised to see this annoying behavior. Probably split window would make it less annoying and possibility to close splint window with one key press like ENTER or something like that, would make it behave as it was before.

If things do not fit into split window one can always move that window to another tab with `:tabedit %`, or can maximize it with `<C-W>_`.

**Comment by tpope** [comment]
I agree, Neovim is annoying.

Split does sound like a better default.

**Pull request closed without merging**
