### PR TITLE
Ggrep suppport browsing and jumping to matching files

### PR DESCRIPTION
**Pull request by tomerf**
I created an interactive grep that opens a small window with the matches and allows to view the matching files and jump directly to the matches (file and line).

I based the code on Gblame and it looks pretty good IMO. I'm not an expert on vimscript (just enough to constantly tweak my own .vimrc) but as far as I tested it things are working well. Feel free to change it if you think it can be done better.

PS: I removed the Glgrep command. As far as I can see 'grep' is hard coded and (re)assigned to the 'cmd' argument without checking the original value, so there's really no difference. Same for Gllog, but I didn't touch it.
PS2: Add this line to .vimrc to grep the word under the cursor:
```nnoremap <leader>gg "zyiw:Ggrep \<<C-R>z\><CR>```

### CODE REVIEW

**Comment by tpope** [comment]
The quickfix is ugly but it works; I don't see a good enough reason for reinventing it.

Glgrep definitely works. Search for `a:cmd`.

**Comment by tomerf** [comment]
What quickfix? The original grep is broken. I get a list of all matches and then it just go to the first one. No option to scroll and no option to choose what match I want, or even cancel and stay on the same file.

**Comment by tomerf** [comment]
As for the lgrep, my bad. But llog doesn't work: ```let cmd = ['--no-pager', 'log', '--no-color']```

**Comment by tpope** [comment]
:help :make
    :help :copen

**Comment by tpope** [comment]
`a:cmd` and `cmd` are 2 unrelated variables.

**Comment by tomerf** [comment]
Nice, the quickfix window is definitely better.

As I said, it doesn't open the window so I added an explicit call copen/lopen on ":Ggrep!" and made the grep call silent (seems to work only in gvim, not vim). Should I open a new pull request for that?

**Comment by tpope** [comment]
FAQ addresses why `:Ggrep` works the way it does.

**Pull request closed without merging**
