### PR TITLE
#547 Add support for core.commentChar.

### PR DESCRIPTION
**Pull request by croesch**
Trying to solve #547 I would like you to have a look on my PR.

Please review the code style and my changes, especially the occurrences of `#` that I didn't touch!

I thought it would be necessary to escape the comment char (since it seems to be used in regular expressions) but I wasn't able to find a good way, anyway I created `s:repo_commentchar_escaped()` for that purpose. Can you help me with that? Surprisingly my special configuration `core.commentChar = $` seems to work after that PR, at least `-` is working in `:Gstatus`.

Consider this PR a draft and regarding to
>What takes you hours might take me minutes simply because I have both domain knowledge and a perverse knowledge of VimScript so vast that many would consider it a symptom of mental illness.

I'm looking forward reading your advices :)

### CODE REVIEW

**Comment by tpope** [comment]
How do you plan to fix the syntax highlighting? This is a massive change for a partial solution. I think it'd be much simpler to just force `-c core.commentChar '#'` when we call `git status`.

Easiest way to escape is just by wrapping the character in square brackets.

**Comment by tpope** [comment]
Where to begin. The concrete facts are that forcing `-c core.commentChar='#'` on `:Gstatus` would have no effect on any commit message. And `[[]` and `[]]` are valid.

It is my personal opinion that starting a commit message with `#issue-number` is a fool's errand. Does everyone who contributes to the project need to set that option too? Do they all need to go send pull requests to their respective editor tooling adding a bunch of special support? All so they can use some slightly different notation you just invented? Do you think this notation is so superior that the entire world will flock to it once it gains traction, and the short term pain is outweighed by the long term gain? Or do you just plan on slightly inconveniencing everyone around you indefinitely?

**Comment by croesch** [comment]
I agree, a pragmatic solution.. I changed the obvious (to me) ones and left for example all `#\t` to use the comment char instead of dot.

What do you think about that set?

**Comment by tpope** [comment]
The `Stage` functions are probably all fine to use `.`. Those buffers are 100% comments and there will never be a commit message to cause a false positive.

Repeatedly shelling out to `git config` is not an option. Do that in `foldtext` on Windows and you've rendered the editor completely unusable.

**Comment by croesch** [comment]
OK .. I'll fix that.

What do you recommend when to call git config? Once per command / function or is that too often, too?

**Comment by aschrab** [comment]
@croesch Are you aware of #689? I've been using that for a long time now without issues. It seems to handle this without needing to call `git config` at all.

**Comment by tpope** [comment]
The Windows `system()` experience is unconditionally bad, and it can get painful even on UNIX if you're doing IO in the background. I think it needs to be fully cached and only called once per repo. This is a pain, and I highly recommend you try to avoid it. Consider `[[:punct:]]` in places where `.` seems too broad.

The patch looks like a blind search and replace. There's several places where something like `line ==# '#'` was changed to `line ==# '.'` which is obviously not going to work.

**Comment by croesch** [comment]
@aschrab thanks, but unfortunately I was not ..

@tpope I'll add the caching.. It might look like but it is no *blind* search and replace. I still don't see ony occurence that looks like `==# '.'`. All `==# '#'` currently use the function to evaluate the comment char.. Can you give me one line number of those *several* places? I'll fix it then, too ..

**Comment by tpope** [comment]
Searching for `==# '.` finds 5 matches.

**Comment by tpope** [comment]
Rendered moot by the new `:Gstatus`.

**Pull request closed without merging**
