### PR TITLE
Ggrep: use current working directory

### PR DESCRIPTION
**Pull request by dmerejkowsky**
Also, always call git with
 --git-dir and
 --work-tree

Fixes issue #753

### CODE REVIEW

**Comment by tpope** [comment]
So what happens if the working directory isn't under the work tree at all?

**Comment by dmerejkowsky** [comment]
Hum. Did not think of this use case. 

Let's assume you have a repo in `/path/to/repo` , and `/path/to/repo/bar/baz` that matches `foo`

If you run

```
:e /path/to/repo/some-file
:Ggrep foo
```

you get a quickfix list containing `bar/baz` : it's relative to the git repo and so you cannot open the file directly from the quickfix list.

Without my patch, you do get `/path/to/repo/bar/baz` in the quickfix list.

**Comment by tpope** [comment]
As a compromise, `:Ggrep pattern .` now works to target a subdirectory. I don't think doing more than that is tenable.

**Comment by dmerejkowsky** [comment]
> As a compromise, :Ggrep pattern . now works to target a subdirectory. I don't think doing more than that is tenable.

Excellent idea, I like it :)

**Pull request closed without merging**
