### PR TITLE
fix documentation for blame map ~

### PR DESCRIPTION
**Pull request by AlterDepp**
In blame window `[count]~` means the [count]th first parent, not grandparent

### CODE REVIEW

**Comment by tpope** [comment]
Wow how on Earth did that get messed up? Let's ditch the "first" too, "4th first parent" makes no sense.

**Comment by tpope** [comment]
Oh that plays weird against the next line. I'll think on it and figure something out.

**Comment by AlterDepp** [comment]
The git documentation is weird, too. Maybe shorter is better.

**Comment by tpope** [comment]
Yeah simplest is best. "Like HEAD" is misleading too, because it's "like" HEAD, but it's not actually HEAD, it's the commit you're already looking at.

**Pull request closed without merging**
