### PR TITLE
Add built-in package management installation way to the README 

### PR DESCRIPTION
**Pull request by pesarkhobeee**
Dear @tpope 
I am a new user in vim then I found your awesome plugins for that and I really appreciate your efforts 
The only problem was about installing them inside the new version which I knew we don't have to use an external package manager, therefore, I just added the missing part in order to make it easier to install for the people like myself :)

### CODE REVIEW

**Comment by tpope** [comment]
I have my own boilerplate for this which you can find in commentary.vim's README among other places. Feel free to port that over. :slightly_smiling_face:

**Comment by pesarkhobeee** [comment]
@tpope I think right now it is ready :)

**Comment by tpope** [comment]
The shell commands are good. I want to keep parity with the explanatory text as well.

**Comment by pesarkhobeee** [comment]
@tpope done

**Comment by pesarkhobeee** [comment]
@tpope huum I was thinking maybe you forgot this pull request! :)

**Pull request merged**
