### PR TITLE
Checkout multiple files in visual mode #944

### PR DESCRIPTION
**Pull request by dhruvasagar**
Changes to allow checkout of multiple files in visual mode from the Git Status window, similar in function to how Staging works. Let me know what you think.

### CODE REVIEW

**Comment by dhruvasagar** [comment]
Can someone take a look at this ? Would love if this can be merged.

**Comment by dhruvasagar** [comment]
@tpope any thoughts ?

**Comment by tpope** [comment]
@dhruvasagar, what happens to the multiple echomsg lines? The reason I haven't hooked this up myself is I want the recovery situation to be top notch before allowing the user to shoot themselves in the foot this hard.

(Reposting from #944 because it really belongs here.)

**Comment by dhruvasagar** [comment]
@tpope Yea even I haven't been using this particularly, although I do think it may be useful. I can remove the echomsg, are there any other changes you think I should make ? (i'll rebase with latest)

**Comment by tpope** [comment]
My *entire* objection to this feature is that I want to make sure it is possible to undo if you accidentally checkout multiple files. Deleting the `echomsg` would hide the undo instructions and literally make it impossible to undo. So no, do not remove it; it's the worst possible thing you could do.

I would not bother rebasing at this time. Adding the while loop is easy enough. It's figuring out how to handle undo that's hard.

**Comment by dhruvasagar** [comment]
Yea this one was almost 2 years old, looks like a lot has changed. Thanks.

**Pull request closed without merging**
