### PR TITLE
Throw joined errors if error is empty on commit

### PR DESCRIPTION
**Pull request by gautaz**
Fix tpope/vim-fugitive#907
Replace tpope/vim-fugitive#909

### CODE REVIEW

**Comment by gautaz** [comment]
@tpope Does this PR complies better with your guidelines than #909?
If not, can you detail please?

**Comment by gautaz** [comment]
@tpope I guess you are a little busy for now, can you please just confirm that the PR will be considered at some time ?

**Comment by tpope** [comment]
I've been hesitant to take this approach because it can result in a *really* long single line error, but I guess I'll give it a try.

Chill with the aggressive followups, you're not helping your case.

**Comment by gautaz** [comment]
Sorry, I did not mean to be rude, as I'm not an english native, I wasn't sure I had followed the guidelines in the right way.
Thanks for the update and for trying the PR, I'd be happy to modify it if an acceptable alternative is found.

**Pull request merged**
