### PR TITLE
Fix diffoff command.

### PR DESCRIPTION
**Pull request by coot**
`:diffsplit` records settings (like `cursorbind`, `scrollbind`), and
`:diffoff` resotres them.  So if you want to set up `cursorbind` it is
better after executing `:diffsplit`.

Version of #538 but rebased on master.

### CODE REVIEW

**Comment by coot** [comment]
I am not really sure why the git commit message check fails.

**Comment by sinisterstuf** [comment]
It could be the full stop at the end of the summary line.

**Comment by coot** [comment]
Indeed it was, the full stop.

**Comment by tpope** [comment]
Oh, the fact Vim restores rather than resets to default was the piece I was missing. I don't really like bouncing back and forth between windows like that - I assume it fires a bunch of unnecessary `WinEnter` and `WinLeave` events - but if the current behavior is causing a problem I'll accept it.

**Comment by tpope** [comment]
I've removed the line because Vim automatically sets `'cursorbind'` for diff buffers. I assume I added it because there was a window after the feature was added before it was set automatically.

**Pull request closed without merging**
