### PR TITLE
commit --fixup

### PR DESCRIPTION
**Pull request by still-dreaming-1**
This is the commit --fixup workflow requested in issue #303. Let me know if you like the general idea, and if you do, what I need to change before you can merge it.

### CODE REVIEW

**Comment by justinmk** [comment]
I did something related in https://github.com/tpope/vim-fugitive/pull/786 but TBH I've been happy with this simple mapping:

    nnoremap UF :Gcommit --fixup=

To fixup head, just enter `@` (git alias for HEAD):

    :Gcommit --fixup=@

otherwise paste whatever hash you just yanked from somewhere, or use fugitive's `<C-R><C-G>` mapping to paste the current object hash.

Given how simple this is I'm not sure it needs to be built-in.

**Comment by still-dreaming-1** [comment]
@justinmk Interesting. Maybe I should change the mapping from C-f to cf. That would be more along the lines of the other mappings. Also, it would be more Vimlike, control should not be used if when there is a better fit out there. If I understand your comments from your pull request, you did not think the workflow was sufficient because you could not tab through different commit ids. Is that right? This brings up the output from `:Git! log`, but it also overrides the enter key mapping so that it selects the commit id from whatever line the cursor is on. So in my opinion, this is even nicer than tabbing through commit ids because you also see the log. Another nice thing is the cursor starts on the line with the commit id of the previous commit, so if you want to use that one, you just press enter.

I think I will add a mapping so that `n` jumps to the next commit. Unless there is already something like that? I'm not sure where the mappings from that buffer are defined. I don't see them from in the fugitive code, but I discovered by accident that pressing enter brings up more details about a commit, that is before I overrode that mapping. But you can still use that mapping if you bring up `:Git! log` yourself. Maybe `f` should be used instead of enter to select the commit so I don't have to override that mapping...Speaking of which, where is the original enter mapping defined in the code that brings up a diff for that commit? Is that even a fugitive thing? How do I go back to the log from there?

**Comment by bbinet** [comment]
I also think `cf` is a better mapping than `C-f` because it will be more consistent to the `cA`, `ca` commit --amend mappings.

**Comment by bbinet** [comment]
Also +1 for using the `f` key to select the commit to fixup, because it could be useful to still be able to see the full commit description when pressing `enter`

**Comment by bbinet** [comment]
When selecting a commit to fixup, it could also be useful to ask the user if Fugitive should also rebase with autosquash (`git rebase -i --autostash commit^`)

**Comment by still-dreaming-1** [comment]
Now I have it so that you press `cf` instead of `Control-f` from the `:Gstatus` buffer. Also, you press `f` instead of `enter` to select a commit id from the log.

@bbinet The auto-rebase option is interesting. I'm not sure if I like it or dislike it... What do other people think?

Before we get too carried away, what does @tpope think of all this? Is there any chance this pull request will get merged at some point?

**Comment by still-dreaming-1** [comment]
Now I got it so that once the log is displayed during this workflow, you press `n` or `N` to jump to the next or previous commit.

**Comment by still-dreaming-1** [comment]
@bbinet After further thought, I agree it would be nice for fugitive to ask you if you want to do an autosquash like that as that is typically why you are doing a fixup commit. That would help you to keep a clean commit history as you work rather than leaving it to cleanup at some future point.

I will do some research on getting Vim to ask the user a question, but I don't believe I have ever written that functionality into a plugin before.

**Comment by still-dreaming-1** [comment]
It is asking the user and doing that autosquash rebase now. I went through the full workflow, imagining I was just hacking on some project and wanting to do that stuff with git. Combined with the rebase it is a pretty sweet workflow. I need to improve the way that last part works as at least on my system it ends up running Neovim inside of Neovim, which somehow did not cause any problems for me...

**Comment by still-dreaming-1** [comment]
I just wanted to summarize the idea behind the complete workflow in case that adds clarity of why the autosquash at the end is good.

You do a commit. Then you do some more work. You realize it is just more of the same from the previous commit, perhaps the previous commit could even be considered "unfinished". So you want to do a fixup commit. No problem, just stash the changes from `:Gstatus`, and then use `cf` to do a fixup commit. It brings up the log so you can select a commit. The first one is what you want so you immediately press `f` to use that as your fixup commit. It asks you if you want to do the rebase. You just want your latest commit to be a part of the previous one, so you are happy this makes the whole process feel like an atomic operation. So you type `y` and press enter. Done. You see the interactive rebase buffer. Everything looks good, so you save and quit (this part needs adjusting), leaving you looking at the original file you were editing.

Done. There is nothing stopping you from doing a more complex interactive rebase later on, if that is your cup of tea, but now that last commit has been cleanly combined as part of the previous one.

**Comment by bbinet** [comment]
@still-dreaming-1 thanks, it looks great!

**Comment by still-dreaming-1** [comment]
So opening Neovim inside of Neovim for the interactive rebase buffer was a result of having nvim set as the default editor for my system. It actually did not cause any problems, it is just a little strange. I'm not sure how to avoid that, am I am open to suggestions, but it was not a big deal for me.

I tried setting vim as the default better and the experience was a little nicer. It opened up a new instance of Vim for that buffer. Once it closed, I saw some output in the terminal, and then it went back to the original Vim instance. I'm not sure why Vim works nicer, but maybe there is something to learn from that to get Neovim to work the same way? I don't know if Vim works differently because of some special handling on the side of fugitive or if that is just a Vim thing.

**Comment by justinmk** [comment]
> I'm not sure why Vim works nicer, but maybe there is something to learn from that to get Neovim to work the same way? 

It's because `:!vim` works in terminal-Vim. `:!` uses pipes so it works consistently in all UIs, but for interactive terminal applications `:terminal` is needed (which fugitive uses for nvim instead of `:!`).

We could actually fake Vim's `:!vim` behavior with `:terminal` (and it would even work in GUIs), so that it works like terminal-Vim's `:!vim`. But it might be a better use of time to figure out specifically what strangeness you observed and see how we can address that.

**Comment by still-dreaming-1** [comment]
@justinmk Well nothing bad happened. But I could see both Neovim's at the same time. I could see Neovim running inside of Neovim. I guess it is ok like that, but I'm not sure.

**Comment by still-dreaming-1** [comment]
There has not seen any activity in the way of comments for a while, and I am happy with it now, so I did a rebase and brought it down to a single commit, which seems right given how little has changed. I also updated the documentation to fix something I forgot to change and, also in the documentation, I explained a little about what the rebase question at the end is for.

**Pull request closed without merging**
