### PR TITLE
Optimize fugitive#foldtext

### PR DESCRIPTION
**Pull request by blueyed**
Only really relevant when using `set cursorline` [1], but good in
general after all.

1: https://github.com/vim/vim/issues/2773

### CODE REVIEW

**Comment by tpope** [comment]
That `modified|renamed` change is going to screw up non-English locales. Other than that looks good.

**Comment by blueyed** [comment]
It only changes the quoting style compared to the original version, doesn't it?

**Comment by tpope** [comment]
No, it replaces `[[:alpha:] ]+` with hard coded labels.

**Comment by blueyed** [comment]
Are you mixing up lines?

This is from the diff:

```diff
-    cal map(lines,'s:sub(v:val, "^#\t%(modified: +|renamed: +)=", "")')
-    cal map(lines,'s:sub(v:val, "^([[:alpha:] ]+): +(.*)", "\\2 (\\1)")')
-    return getline(v:foldstart).' '.join(lines, ', ')
+    cal map(lines, "s:sub(v:val, '^#\t%(modified: +|renamed: +)=', '')")
+    cal map(lines, "s:sub(v:val, '^([[:alpha:] ]+): +(.*)', '\\2 (\\1)')")
+    return line_foldstart.' '.join(lines, ', ')
```

`modified|renamed` is on another line in the original code than the `[[:alpha:] ]+` already, and both are kept.
I could not figure out what the `([[:alpha:] ]+):` is supposed to match btw, but it appears to just swap `foo: bar` into `bar: foo`?

**Comment by tpope** [comment]
You're right, I am mixing up lines.

**Pull request merged**
