### PR TITLE
Correct the directory separator of Path in the windows environment

### PR DESCRIPTION
**Pull request by RyoSusami**
Patch for error from commit 07d30de in the windows environment.

### CODE REVIEW

**Comment by tpope** [comment]
Thanks for looking out, can you just call `s:shellslash()` on the path and drop the conditional?

**Comment by RyoSusami** [comment]
Thank you for pointing, I pushed the patch using s: shellslash().

**Comment by tpope** [comment]
Thanks! This is clearly the correct logic, but can you clarify the error this was causing? So I can avoid future mistakes like this.

**Comment by tpope** [comment]
Makes perfect sense, thanks!

**Pull request merged**
