### PR TITLE
Removing change directory step from pathogen installation step.

### PR DESCRIPTION
**Pull request by Khalian**

### CODE REVIEW

**Comment by tpope** [comment]
Breaks the very next line.

**Comment by Khalian** [comment]
@tpope Are you referencing vim -u NONE -c "helptags vim-fugitive/doc" -c q?

There should be no reason a developer needs to be under a certain directory to launch vim.

**Comment by tpope** [comment]
`:helptags` with a relative path most certainly depends on the current working directory.

**Comment by Khalian** [comment]
Ok, does the path change work on the vim arg good?

**Comment by tpope** [comment]
New rule: no bikeshedding installation instructions. I maintain them for 50ish Vim plugins and they're already badly out of sync without external meddling.

**Pull request closed without merging**
