### PR TITLE
Move most code to the autoload directory.

### PR DESCRIPTION
**Pull request by lucc**
See #376.

The code was moved with minimal changes.  The result according to `--startuptime` if no file under git is opened:

```
old:313.497  005.805  005.805: sourcing /home/luc/.local/share/vim/bundle/vim-fugitive/plugin/fugitive.vim
new:304.365  000.131  000.131: sourcing /home/luc/.local/share/vim/bundle/vim-fugitive/plugin/fugitive.vim
```

**Please test this PR with all the different "entry points" to fugitive.  I do not know and use all of them so I might not have detected some breakage which might be due to this move.**

### CODE REVIEW

**Comment by tpope** [comment]
I'm confused by your results as I would expect the `VimEnter *` autocommand to trigger a fugitive load. At any rate I think we need a `FugitiveDetect()` in the plugin file to cope with basically every other case.

**Comment by lucc** [comment]
I see. I did only test a vim start with no file, not a start with a file that is not under git. Sorry, I will try to update the PR.

**Comment by lucc** [comment]
I rebased my changes on the latest master. But now I don't see the problem you mentioned any more. Do you still get it?

I tried to open an empty buffer or a file not under git -> no commands defined
I opened a file under git from the command line and in vim -> commands defined and *seem* to work (only tested some)

**Comment by justinmk** [comment]
@lucc With this functionality (which still exists in your PR):

    autocmd VimEnter * if expand('<amatch>')==''|call fugitive#detect(getcwd())|endif

the move to autoload is almost pointless, it will autoload fugitive (don't know why you aren't seeing that, but a call to `fugitive#foo` will source `autoload/fugitive.vim`). 

One would need to move detection to `plugin/fugitive.vim` (the `FugitiveDetect()` @tpope mentioned) to avoid autoloading the entire thing.  The `BufNewFile,BufReadPost` and other handlers also call `fugitive#detect` so again in every case fugitive will be loaded. Those `fugitive#detect` calls need to be replaced with `FugitiveDetect()`.

**Comment by neersighted** [comment]
I really would appreciate this change as fugitive is a big chunk of my startuptime as well. @lucc, the change is pretty simple, some of the code cannot be autoloaded as it runs on every file load. If you don't have time, I'd be glad to PR the changes to your branch. Let me know.

**Comment by lucc** [comment]
@neersighted sorry I had other stuff to do. If you have the time and send a PR for my branch I will merge it.

**Comment by neersighted** [comment]
@lucc Just wanted to note (two years later, hah), that this work appears to have been done in master, and this PR is now obsolete.

**Comment by lucc** [comment]
@neersighted thanks for the heads up.

**Pull request closed without merging**
